[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20.15.1" }

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 